### ISSUE TITLE
College/University IP claims?

### ISSUE THREAD

**Issue by ryantheleach** [ArduinoHistory/arduinohistory.github.io#5]
I have no idea, but after reading your blog post I have to wonder, does the university not have IP claims over work produced from Hernando's thesis?

**Comment by bhagman** [comment]
Hi Ryan,

I can't be 100% certain on this one, so it would be nice to have some help digging into it. Here are a some things to note:
1. IDII is closed.  There is no IDII organization, AFAIK.
2. Academic institutions rarely have policies that indicate the institution has copyright over the dissertation/thesis.  Most cases, where the institution has copyright, is when the student is employed by the institution.  There are a LOT of fringe cases, however.  It would be nice to have a definitive answer.

It would be nice to get someone from IDII to state what the policy was for copyright over graduate theses.  Better yet, a copy of the IDII policy would be ideal.

Despite the absence of the policy and the fact the institution is closed, more than likely, IDII did not have any copyright over Hernando's thesis.  Besides, the thesis has been made public ever since Hernando graduated, and was made publicly available on the IDII website (and continues in a 2006 mirror of the institution's website).

http://people.interactionivrea.org/h.barragan/thesis/thesis_low_res.pdf
